### ISSUE TITLE
Fix unreachable servers

### ISSUE THREAD

**Issue by gregor160300** [AurousGroup/aurous.me#9]
Hi, since everyone notices you guys are having trouble with keeping your servers stable, maybe you can host your website on github as an alternative, for if the main site is down, also could you at least provide latest installers for every platform on github?

**Comment by dmxt** [comment]
We're currently upgrading the server, please be patient with us.

**Comment by onezetty** [comment]
Nice, tnx for the update :)

**Comment by gregor160300** [comment]
I know, just trying to save your money, keep ip the good work :)
